proyecto/project/blog/urls.py
from django.urls import path
from blog.views import PostList, categoria

app_name = "blog"

urlpatterns = [
    path('', PostList.as_view(), name="blog"),
    path('categoria/<int:categoria_id>',categoria,name="categoria")
]

proyecto/project/login/urls.py
from django.urls import path
from login.views import CustomLoginViews, register, cerrar_sesion
from django.contrib.auth.views import LogoutView

app_name = "login"

urlpatterns = [
    path("''", CustomLoginViews.as_view(), name="login"),
    path("logout/",cerrar_sesion, name="logout"),
    path("register/",register,name="register")
]

proyecto/project/producto/urls.py
from django.urls import path
from producto.views import Home
from django.conf import settings
from django.conf.urls.static import static
#from config import views

app_name = "producto"
urlpatterns = [
   path('',Home,name="home"),
]

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

proyecto/project/project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("producto.urls")),
    path('servicios/',include("servicios.urls")),
    path('blog/',include("blog.urls")),
    path('contacto/',include("contacto.urls")),
    path('tienda/',include("tienda.urls")),
    path('carro/',include("carro.urls")),
    path('login/',include("login.urls")),
]

proyecto/project/tienda/urls.py
from django.urls import path
from tienda.views import TiendaList, categoria_producto


app_name = "tienda"
urlpatterns = [
   path('',TiendaList.as_view(),name="tienda"),
   path('tienda/categoria/<int:categoria_id>',categoria_producto,name="categoria_producto")
]

proyecto/project/login/models.py
from django.db import models

# Create your models here.

proyecto/project/login/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

class CustomAuthenticationForm(AuthenticationForm):
    class Mete:
        model = User
        fields = ["username", "password"]

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username","password1","password2"]

proyecto/project/login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from .forms import CustomAuthenticationForm, CustomUserCreationForm
from django.http import HttpResponse, HttpRequest
from django.contrib.auth import logout

def index(request):
    return render(request,"core/index.html")

class CustomLoginViews(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = "login/login.html"

def register(request: HttpRequest):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            form.save()
            return render(request, "producto/home.html", {"mensaje": f"Usuario '{username}' creado correctamente"})
    else:
        form = CustomUserCreationForm
    return render(request, "login/register.html",{"form": form})


def cerrar_sesion(request):
    logout(request)
    
    return redirect("producto:home")
    

proyecto/project/login/templates/login/login.html
{% extends 'producto/base.html' %}
{% load static %}

{% block body_tittle %}
<span class="site-heading-lower">Login</span>
{% endblock body_tittle %}

{% block content %}
<div class="container mt-5 mb-5"> <!-- Agregamos márgenes top (mt-5) y bottom (mb-5) -->
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <div class="form-group">
              {{ form.username.label_tag }}
              {{ form.username }}
            </div>
            <div class="form-group">
              {{ form.password.label_tag }}
              {{ form.password }}
            </div>
            <input type="hidden" name="next" value="{% url 'tienda:tienda' %}" />
            <button type="submit" class="btn btn-secondary btn-block mt-2 bg-dark text-white">Iniciar Sesión</button>
            <a href="{% url 'producto:home' %}" class="btn btn-secondary btn-block mt-2 bg-dark text-white">Cancelar</a>
            <br>
            <p style="text-align: center;">¿Aun no estas registrado?</p>
            <a href="{% url 'login:register' %}" class="btn btn-primary btn-block mt-2">Registrate</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

proyecto/project/login/templates/login/register.html
{% extends 'producto/base.html' %}
{% load static %}

{% block body_tittle %}
<span class="site-heading-lower">Servicios</span>
{% endblock body_tittle %}

{% block content %}
<div class="container mt-5 mb-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <div class="form-group">
              {{ form.as_table }}
            </div>
            <input type="hidden" name="next" value="{% url 'producto:home' %}" />
            <button type="submit" class="btn btn-secondary btn-block mt-2 bg-dark text-white">Crear Cuenta</button>
            <a href="{% url 'producto:home' %}" class="btn btn-secondary btn-block mt-2 bg-dark text-white">Cancelar</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}