proyecto/project/blog/urls.py
from django.urls import path
from blog.views import PostList, categoria

app_name = "blog"

urlpatterns = [
    path('', PostList.as_view(), name="blog"),
    path('categoria/<int:categoria_id>',categoria,name="categoria")
]

proyecto/project/carro/urls.py
from django.urls import path
from . import views
from carro.views import carro

app_name = "carro"
urlpatterns = [
    path('',carro,name="carro"),
    path('agregar/<int:producto_id>',views.agregar_producto,name="agregar"),
    path('eliminar/<int:producto_id>',views.eliminar_producto,name="eliminar"),
    path('restar/<int:producto_id>',views.restar_producto,name="restar"),
   
]

proyecto/project/contacto/urls.py
from django.urls import path
from contacto.views import Contacto


app_name = "contacto"
urlpatterns = [
   path('',Contacto,name="contacto"),
]

proyecto/project/login/urls.py
from django.urls import path
from login.views import CustomLoginViews, register, cerrar_sesion
from django.contrib.auth.views import LogoutView

app_name = "login"

urlpatterns = [
    path("''", CustomLoginViews.as_view(), name="login"),
    path("logout/",cerrar_sesion, name="logout"),
    path("register/",register,name="register")
]

proyecto/project/producto/urls.py
from django.urls import path
from producto.views import Home
from django.conf import settings
from django.conf.urls.static import static
#from config import views

app_name = "producto"
urlpatterns = [
   path('',Home,name="home"),
]

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

proyecto/project/project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("producto.urls")),
    path('servicios/',include("servicios.urls")),
    path('blog/',include("blog.urls")),
    path('contacto/',include("contacto.urls")),
    path('tienda/',include("tienda.urls")),
    path('carro/',include("carro.urls")),
    path('login/',include("login.urls")),
]

proyecto/project/tienda/urls.py
from django.urls import path
from tienda.views import TiendaList, categoria_producto


app_name = "tienda"
urlpatterns = [
   path('',TiendaList.as_view(),name="tienda"),
   path('tienda/categoria/<int:categoria_id>',categoria_producto,name="categoria_producto")
]

proyecto/project/producto/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic import ListView
from django.db.models.query import QuerySet
from carro.carro import Carro



def Home(request):
    carro = Carro(request)
    return render(request,"producto/home.html")

proyecto/project/producto/templates/producto/base.html
<html>

<head>

     {% load static %}
    <!-- Bootstrap -->
    <link href="{% static 'producto//vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

     <!-- Fonts -->
    
     <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet"> 
     <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
     

    <!-- Styles -->
    <link href="{% static 'producto//css/gestion.css' %}" rel="stylesheet">
</head>

<body>

    <h1 class="site-heading text-center text-white d-none d-lg-block">
      {% block body_tittle %}
      <span class="site-heading-lower">Sport Shop</span>
      {% endblock body_tittle %}
        
      </h1>


 <!-- Navbar -->
 <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav" style="background-color: rgb(245, 86, 12)">
  <div class="container d-flex justify-content-between">
      <!-- Logo en la parte izquierda -->
      <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="home.html">Gestión de Pedidos</a>
      <!-- Botón para colapsar en dispositivos pequeños -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Elementos en el centro -->
      <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav mx-auto">
              <li class="nav-item {% if request.path == '/' %} active {% endif %} px-lg-4">
                  <a class="nav-link text-uppercase text-expanded" href="{% url 'producto:home' %} ">Inicio</a>
              </li>
              <li class="nav-item {% if request.path == '/servicios/' %} active {% endif %} px-lg-4">
                  <a class="nav-link text-uppercase text-expanded" href="{% url 'servicios:servicios' %} ">Servicios</a>
              </li>
              <li class="nav-item {% if request.path == '/tienda/' %} active {% endif %} px-lg-4">
                  <a class="nav-link text-uppercase text-expanded" href="{% url 'tienda:tienda' %} ">Tienda</a>
              </li>
              <li class="nav-item {% if request.path == '/contacto/' %} active {% endif %} px-lg-4">
                  <a class="nav-link text-uppercase text-expanded" href="{% url 'contacto:contacto' %}">Contacto</a>
              </li>
              <li class="nav-item {% if request.path == '/blog/' %} active {% endif %} px-lg-4">
                  <a class="nav-link text-uppercase text-expanded" href="{% url 'blog:blog' %}">Blog</a>
              </li>
          </ul>
      </div>
      <!-- Elementos en la parte derecha -->
      <div>
          {% if user.is_authenticated %}
          <ul class="navbar-nav">
              <li class="nav-item {% if request.path == '/carro/' %} active {% endif %} px-lg-4">
                  <a class="nav-link text-uppercase text-expanded bi bi-cart4" href="{% url 'carro:carro' %}">Carro</a>
              </li>
              <li class="nav-item px-lg-4 bg-dark">
                  <a class="nav-link text-uppercase text-expanded" href="#">{{user.username}}</a>
              </li>
              <li class="nav-item px-lg-4">
                  <a class="nav-link text-uppercase text-expanded" href="{% url 'login:logout' %}">Logout</a>
              </li>
          </ul>
          {% else %}
          <ul class="navbar-nav">
              <li class="nav-item {% if request.path == '/carro/' %} active {% endif %} px-lg-4">
                  <a class="nav-link text-uppercase text-expanded" href="{% url 'carro:carro' %}">Carro</a>
              </li>
              <li class="nav-item {% if request.path == '/login/' %} active {% endif %} px-lg-4">
                  <a class="nav-link text-uppercase text-expanded" href="{% url 'login:login' %}">Login</a>
              </li>
          </ul>
          {% endif %}
      </div>
  </div>
</nav>

     <!-- Contenido cambiante -->
     {% block content %}
      
     {% endblock content %}
  


    <!-- Footer -->
    <footer class="footer text-faded text-center py-5">
      <div class="container">
        <p class="m-0">
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	    </p>
        <p class="m-0 mbt">
        	<a href="sample.html" class="link">Política de privacidad</a> ·
        	<a href="sample.html" class="link">Aviso legal</a> ·
        	<a href="sample.html" class="link">Cookies</a>
		</p>
        <p class="m-0 mbt1">&copy; Gestión de Pedidos 2020</p>
      </div>
	</footer>

    <!-- Bootstrap -->
    <script src="{% static 'producto//vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'producto//vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>


</html>

proyecto/project/producto/templates/producto/home.html
{% extends 'producto/base.html' %}
{% load static %}

{% block content %}
    
    <div style="text-align: center; color: white;">
      {% if user.is_authenticated %}
            <p class = "font-weight-bold"> ¡Bienvenido! {{user.username}}</p>
        {% endif %}

      {% if mensaje %}
         <p class = "font-weight-bold"> {{mensaje}} ¡Bienvenido! </p>
        {% endif %}
      
    </div>



   <!-- Heading -->
   <section class="page-section clearfix">
    <div class="container">
      <div class="intro">
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'producto/img/zapas.jpg' %}" alt="">
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4 " >
            <span class="section-heading-upper">Calidad Garantizada</span>
            <span class="section-heading-lower">El mejor stock</span>
          </h2> 
          <p class="mb-3">Podes encontrar todo sobre articulos deportivos tanto en nuestra tienda fisica y nuestra tienda online. Con envios en menos de 48hs.
          </p>
         
        </div>
      </div>
    </div>
  </section>


  
    <!-- Message -->
    <section class="page-section cta">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-inner text-center rounded">
              <h2 class="section-heading mb-4">
                <span class="section-heading-upper">Compromiso total</span>
                <span class="section-heading-lower">Garantizado</span>
              </h2>
              <p class="mb-0">Con más de 20 años de experiencia a nuestras espaldas, desde Sport Shop tenemos los conocimientos y la experiencia para asesorarte en todo lo que necesitas para un mayor rendimiento deportivo. Y brindarte la comodidad de llevartelo a la puerta de su casa con puntualidad y profesionalidad.</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    {% endblock content %}