proyecto/project/blog/urls.py
from django.urls import path
from blog.views import PostList, categoria

app_name = "blog"

urlpatterns = [
    path('', PostList.as_view(), name="blog"),
    path('categoria/<int:categoria_id>',categoria,name="categoria")
]

proyecto/project/carro/urls.py
from django.urls import path
from . import views
from carro.views import carro

app_name = "carro"
urlpatterns = [
    path('',carro,name="carro"),
    path('agregar/<int:producto_id>',views.agregar_producto,name="agregar"),
    path('eliminar/<int:producto_id>',views.eliminar_producto,name="eliminar"),
    path('restar/<int:producto_id>',views.restar_producto,name="restar"),
   
]

proyecto/project/login/urls.py
from django.urls import path
from login.views import CustomLoginViews, register, cerrar_sesion
from django.contrib.auth.views import LogoutView

app_name = "login"

urlpatterns = [
    path("''", CustomLoginViews.as_view(), name="login"),
    path("logout/",cerrar_sesion, name="logout"),
    path("register/",register,name="register")
]

proyecto/project/project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("producto.urls")),
    path('servicios/',include("servicios.urls")),
    path('blog/',include("blog.urls")),
    path('contacto/',include("contacto.urls")),
    path('tienda/',include("tienda.urls")),
    path('carro/',include("carro.urls")),
    path('login/',include("login.urls")),
]

proyecto/project/carro/views.py
from django.shortcuts import render, redirect, HttpResponse
from .carro import Carro        
from tienda.models import Producto

def carro(request):
    return render(request,"carro/carro.html")

def agregar_producto(request,producto_id):
    carro = Carro(request)
    producto = Producto.objects.get(id = producto_id)
    carro.agregar(producto=producto)
    return render(request,"carro/carro.html",{'carro': carro, 'producto':producto})

def eliminar_producto(request,producto_id):
    carro = Carro(request)
    producto = Producto.objects.get(id = producto_id)
    carro.eliminar(producto=producto)
    return render(request,"carro/carro.html",{'carro': carro, 'producto':producto})

def restar_producto(request,producto_id):
    carro = Carro(request)
    producto = Producto.objects.get(id = producto_id)
    carro.restar_producto(producto=producto)
    return render(request,"carro/carro.html",{'carro': carro, 'producto':producto})
    

def limpiar_carro(request,producto_id):
    carro = Carro(request)
    carro.limpar_carro()
    return redirect("tienda")

proyecto/project/carro/templates/carro/carro.html
{% extends 'producto/base.html' %}
{% load static %}

{% block body_tittle %}
<span class="site-heading-lower">Tienda Online</span>
{% endblock body_tittle %}

{% block content %}
<div class="container mt-5 mb-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body">
          <table class="table table-bordered table-hover">
            <thead class="table-dark">
              <tr>
                <th colspan="3" class="text-center">Carro de Compras</th>
              </tr>
              {% if user.is_authenticated %}
              <tr>
                <th>Producto</th>
                <th>Cantidad</th>
                <th>Total</th>
              </tr>
            </thead>
            <tbody>
              {% if request.session.carro.items %}
              {% for key, value in request.session.carro.items %}
              <tr>
                <td>{{ value.nombre }}</td>
                <td>{{ value.cantidad }}</td>
                <td>
                  <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                  <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-danger">-</a>
                  ${{ value.precio }}
                </td>
              </tr>
              {% endfor %}
              {% else %}
              <tr>
                <td colspan="3">
                  <div class="alert alert-danger text-center">
                    El carro está vacío
                  </div>
                </td>
              </tr>
              {% endif %}
            </tbody>
            <tfoot>
              <tr>
                <td colspan="3" class="text-center">Total: ${{ importe_total_carro }}</td>
              </tr>
              {% if request.session.carro.items %}
              <tr>
                <td colspan="3" style="text-align: center;">
                  <a href="#" class="btn btn-primary">Hacer Pedido</a>
                </td>
              </tr>
              {% endif %}
            </tfoot>
            {% else %}
            <tr class="text-center">
              <td colspan="3">Debes iniciar sesión para comenzar a comprar</td>
            </tr>
            <tr>
              <td colspan="3" style="text-align: center;">
                <a href="{% url 'login:login' %}" class="btn btn-primary">Iniciar sesión</a>
              </td>
            </tr>
            {% endif %}
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}